name: Deployment pipeline

on:
  push:
    branches:
      - main
    pull_request:
      branches: [main]
      types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' 

      - name: Install Client and server Dependencies
        run: npm install

      - name: Test Client side
        run: npm run test || exit 1

      - name: Install Server Dependencies
        run: npm install

      - name: Build Client
        run: npm run build
      