name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.0' 

      - name: Install Client Dependencies
        working-directory: client
        run: npm install

      - name: Test Client side
        working-directory: client
        run: npm run test || exit 1

      - name: Install Server Dependencies
        working-directory: server
        run: npm install

      - name: Build Client
        working-directory: client
        run: npm run build
      